### ISSUE TITLE
Geometric Optics: Basics - Master Checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics-basics#1]
# Geometric Optics: Basics main checklist

## Design
- [ ] **Sim folder and design doc created** (Date: //)
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Review user feedback** 
   - [ ] *If a Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
   - [ ] *If a Port:* [Unfuddle tickets reviewed](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md)
   - [ ] *If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
   - [ ] *If a new sim:* [Unfuddle suggestions reviewed](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: 11/10/2021)
- [x] **Design concept complete**  (Date: 12/20/2021)
- [ ] **Wireframes complete** (Date: //)
- [ ] **Mockups complete** (Date: //)
  - [ ] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [ ] **Interviews complete** (Date: //)
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-prototype items**
  - [ ] Auxilary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive - https://github.com/phetsims/geometric-optics/issues/421
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use) - https://github.com/phetsims/geometric-optics/issues/421
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) - https://github.com/phetsims/geometric-optics/issues/421
  - [x] Create "sim primer" issue - #42 
  - [ ] Hold postmortem if applicable (Date: //)

## Inclusive Features
- [x] Alternative Input (Started: ) (Completed: ) 
- [x] Pan & Zoom
- [x] Sound & Sonification (UI)
- [ ] Sound & Sonification (Pedagogical) - (include link to relevant sonification design document)
    - [ ] Sound design complete (Started: ) (Completed: ) 
    - [ ] Development complete (Started: ) (Completed: ) 
- [ ] Interactive Description - (link to description design & implementation checklist)
    - [ ] Description design complete (Started: ) (Completed: ) 
    - [ ] Development complete (Started: ) (Completed: ) 
    - [ ] Mobile description included
- [ ] Voicing - (include links to relevant voicing design document)

## Implementation
- [x] **Repository created** by following [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md) (Date: 2/21/2022)
- [x] **Development started** (Date: 2/22/2022)
- [x] **Sim is "feature complete"** (Date: 2/22/2022)
- [x] **QA team "first look"** (Date: //)
- [ ] Interviews may happen around here (see above)
- [x] **Code review checklist completed"** (Date: //)
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Sim dev test completed** (Date: 11/7/2022)
- [x] **Sim RC tests completed** (Date: 11/29/2022)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/master/js/CreditsNode.js))
  - [x] Add CT tests for public query parameters
- [x] **Published** (Date: 11/29/2022)

## QA
- [x] ~~*If a Port:* **Legacy sim tested for bugs**; issues reported in repo~~
- [x] **Dev testing started** (Date: 10/31/2022)
- [x] **Dev testing completed** (Date: 11/7/2022)
- [x] **First RC published** (Date: 11/18/2022)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 11/29/2022)

**Comment by arouinfar** [comment]
Geometric Optics: Basics was designed as a spin-off of Geometric Optics. Developement of these sims overlapped, so many of the items in this checklist were not relevant to the process. I've checked off the relevant items and tagged issues that track remaining TODOs (LoL & primer). Closing.
